### ISSUE TITLE
Git Repository no longer in sync with npm package?

### ISSUE THREAD

**Issue by janis-kra** [bpmsoasolutions/jet-builder-cli#1]
Hey there,

first of all, thanks a lot for building this great tool!

I noticed that the version of this package on npm is 1.6.24 but the package.json here on github says 1.6.21 -- is that on purpose or did you just forget the latest version also to github?

**Comment by danibram** [comment]
Hi,
Thanks for the comment!
I forgot to upload that commit, just was little modifications on the internal scss generation. I just uploaded the commit.
